### ISSUE TITLE
API discoverability

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#180]
Discoverability is provided (through HATEOAS) for the service to be able to **evolve** without breaking the clients. Using this concept, the clients do not need to hardcode any URI to use the API except for the base URI and do not need to know anything else than some sort of vocabulary.

We provide some sort of discoverability through HATEOAS. But it is very limited: we don't expose POST, PUT or DELETE endpoints through that discoverability. We also don't provide any templating of the uri (like nexus.example.ch/v0/domains?page={page_size}).

However, if we want to really offer full discoverability, the metadata associated to it will explode compared to the useful resource's metadata. [HAL](https://github.com/vasilakisfil/Introspected-REST#731-user-resource) or [Siren](https://github.com/vasilakisfil/Introspected-REST#741-user-resource) define ways to do it, _polluting_ the responses with discoverability metadata.

There are several solutions to this:
1. Do not attempt to provide a fully evolvable API and as a consequence, hardcode the clients and tight them to a certain API version. This will imply the need to provide things like `v0` or `v1` on the base URI.
2. Use the [OPTIONS verb](https://tools.ietf.org/html/rfc7231#section-4.3.7) to provide discoverability links on a separate resource.
3. Use the [Link HTTP header](https://tools.ietf.org/html/rfc8288) to offer discoverability.
4. Use the [well-know URIs](https://tools.ietf.org/html/rfc5785) to provide discoverability on a separate resource.

Thoughts @MFSY @bogdanromanx @hygt @wwajerowicz ?

**Comment by bogdanromanx** [comment]
Good overview. I think option 1 is simple but the most costly possible solution on the long run; I would definitely not go with that.
It's quite difficult to choose between the others because all of them have their pros and cons depending on the client state. Ideally we should implement all of them (2, 3 and 4) but we should also provide basic information in the `links` predicate. For example, to discriminate between the resource id vs the representation id, the best way of doing that is by injecting information in the response.
I think Option 4 should be used just to provide the API entry points something that could be used to further traverse the resource graph and discover additional ways of interacting with it.
Option 3 is best suited when interacting with a resource, to find additional related resources.
Option 2 would be the most descriptive collection of interactions that you can perform on a resource.

**Comment by umbreak** [comment]
Seems a good idea. We should further develop this issue with examples.

* (3) should be used to display relationships like `outgoing`, `incoming`, `schema`, `downloadUri`, `provenance`.
* (4) like you said can be used like the [SIren](https://github.com/vasilakisfil/Introspected-REST#741-user-resource) proposal.
* (4) could provide links to where to discover the basic resources (basically links to (4)).

Is that correct?

**Comment by bogdanromanx** [comment]
I agree with this separation. ;)
Also, I think the information that you mentioned for (4) should be presented when accessing `/v0`.

**Comment by umbreak** [comment]
Other resources related to this: 

- https://introspected.rest/
- https://www.hydra-cg.com/spec/latest/core/
