### ISSUE TITLE
Add ES support for fields

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#234]

**Comment by olinux** [comment]
Does this issue include the proper handling of special characters in the field names? I noticed that elasticsearch splits field names with dots and colons into nested structures what makes it hard to reuse the index for other purposes (e.g. fast lookups for key fields such as "schema:identifier"). Maybe these "special characters" should be replaced following an agreed convention (e.g. colons become underlines, etc.). Additionally: to make the index useful, it would be great to index the fully expanded field names ("http://schema.org/identifier") instead of ("schema:identifier") to make sure all fields are regarded irrespective of the alias chosen by the uploading instance.

**Comment by umbreak** [comment]
Yes. We should definitely manipulate the payload before indexing it. Expanding the JSON-LD payload before inserting it into ES should be the best approach, since the `fields` provided for filtering should always be URIs (predicates are URIs).

Since we are currently working in v1 this task will be tackled when we reach the ES indexing step.
