### ISSUE TITLE
Index ACLs into Blazegraph

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#26]

**Comment by umbreak** [comment]
We will start indexing all the Events coming from Kafka which contains `read` permissions into blazegraph. We will use the predicate `nx:read` and the value  will be the value contained on the Event's @id field. We will have as many triples as identities we have.
Those triples are stored in an own named graph (in order to perform updates to the graph easily) and have as a `subject` the resource where they belong (if there is a permission event for organizations, the subject will be the id of the organization, etc).
