### ISSUE TITLE
Change to TopQuadrant validator

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#424]

**Comment by umbreak** [comment]
Seems to be feasible. 

There were 2 issues:
1. When there are no shapes selected for validation it still returns a `ValidationReport` that conforms. I created a PR upstream, to get information about how many shapes got selected for validation: https://github.com/TopQuadrant/shacl/pull/40 . Maybe is not going to be accepted because it is not part of the SHACL standard. But in any case, we can use it ourselves.
2. When testing against https://github.com/INCF/neuroshapes , the only issue I've found is that the lateral values have to be explicit. Implicitly there will be conversions from literals to `xsd:string`, `xsd:boolean`, `xsd:integer` and `xsd:double`. The validator is not attempting to do field casting.

The advantages are:
1. No need for the `shapes` predicate to be defined as `"@reverse": "rdfs:isDefinedBy"`. This solves the current bug: https://github.com/BlueBrain/nexus-kg/issues/411
2. Shapes verification out of the box so we can avoid implementing https://github.com/BlueBrain/nexus-kg/issues/363
2. Proper `ValidationReport` (compatible with the SHACL standard). 
3. Support for `or` clause (the current validator doesn't)
4. Support for [rules](https://www.w3.org/TR/shacl-af/)
5. Support for [SPARQL constrains](https://www.w3.org/TR/shacl/#sparql-constraints)

**Comment by MFSY** [comment]
There is still a strong need to use @reverse. It the best way to link a schema with the shapes it defines. This provide with guarantee that later on we can define many other resources within a schema so that we don't lock ourselves to a specific standard in term of schema format.
We need strong justification before removing the "@reverse" in Neuroshapes.

 Can you develop more on why you think that switching to the TopQuadrant shacl validator will remove the need of "@reverse": "rdfs:isDefinedBy to link schemas and shapes ?
