### ISSUE TITLE
Instance properties are not retrieved as part of a search result

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#44]

**Comment by jdcourcol** [comment]
when running a query:
GET https://bbp-nexus.epfl.ch/staging/v0/data/bbp/core/fakecircuit/v0.0.1
I get:
{
 "links": [
   {
     "href": "https://bbp-nexus.epfl.ch/staging/v0/data/bbp/core/fakecircuit/v0.0.1",
     "rel": "self"
   },
   {
     "href": "https://bbp-nexus.epfl.ch/staging/v0/data/bbp/core/fakecircuit/v0.0.1?from=20&size=20",
     "rel": "next"
   }
 ],
 "results": [
   {
     "source": {
       "@id": "https://bbp-nexus.epfl.ch/staging/v0/data/bbp/core/fakecircuit/v0.0.1/1348d38b-7492-4976-aa79-776c3fd5ec28",
       "links": [
         {
           "href": "https://bbp-nexus.epfl.ch/staging/v0/data/bbp/core/fakecircuit/v0.0.1/1348d38b-7492-4976-aa79-776c3fd5ec28",
           "rel": "self"
         },
         {
           "href": "https://bbp-nexus.epfl.ch/staging/v0/schemas/bbp/core/fakecircuit/v0.0.1",
           "rel": "schema"
         }
       ]
     },

I would expect to get the properties as for instance in:
https://jsonplaceholder.typicode.com/users

**Comment by bogdanromanx** [comment]
We've discussed previously on whether we should include the instance values in the list / search results and concluded that we'd like to be able to select which properties should be returned instead of all (considering the context size of an instance the result can become quite large).

@jdcourcol would you be comfortable with a query flag that switches between returning just ids or full instances, defaulting to just ids? There are many situations where ids are sufficient, there's no need to pull the whole thing. We could implement that fairly quickly and discuss the appropriate way to select specific properties.

**Comment by jdcourcol** [comment]
I am good with the flag. 

Having the capability to decide which property to return would a good improvement.

The use case for me is to show a list of instances in the GUI, so the list of IDs is not very helpful for the end user. But I don't actually need all the properties, only a subset of them that are meaningful for the end user to decide which item to select.
and then we can load all the properties for the item the user selected.
