### ISSUE TITLE
Unsupported filters with entire path declared in @context

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus-kg#5]
When testing the new filter feature of the KG API, I attempted to run the following query:
```
{
  "@context": {
    "rdf": "http://www.w3c.org/1999/02/22-rdf-syntax-ns#",
    "foo": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/" 
  },
  "filter": {
    "path": "foo:providerId",
    "op": "eq",
    "value": "1012"
  }
}
```

which works, however the following equivalent isn't:
```
{
  "@context": {
    "rdf": "http://www.w3c.org/1999/02/22-rdf-syntax-ns#",
    "providerId": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/providerId" 
  },
  "filter": {
    "path": "providerId",
    "op": "eq",
    "value": "1012"
  }
}
```

and throws the following error:

```
{
"message": "Unable to parse 'path' as an uri",
"field": "DownField(filter)/DownField(path)",
"code": "IllegalFilterFormat"
}
```

**Comment by umbreak** [comment]
Jena doesn't see @context. providerId as a prefix, so [when trying to expand the Uri](https://github.com/BlueBrain/nexus-kg/blob/501d73480fe4e47442354943cbcc3c00ef730d80/modules/indexing/src/main/scala/ch/epfl/bluebrain/nexus/kg/indexing/filtering/Filter.scala#L58), it does nothing. We should probably provide an alternative way to check for aliases which are defined in the context

**Comment by MFSY** [comment]
First of all let make clear that a complete @context object is computed (by nexus) for each filter json-ld payload submitted  by a user. The two above filters along with their complete @context become (I removed the rdf prefix mapping which is not used at all):

```
{
  "@context": {
     "nxv":"http://localhost/v0/voc/nexus/core/",
     "nxs":"http://localhost/v0/voc/nexus/search/",
      "filter":"nxs:filter",
      "path":"nxs:path",
      "value":"nxs:value",
      "op":"nxs:op",
       "foo": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/" 
  },
  "filter": {
    "path": "foo:providerId",
    "op": "eq",
    "value": "1012"
  }
}
```

and

```
{
   "@context": {
      "nxv":"http://localhost/v0/voc/nexus/core/",
     "nxs":"http://localhost/v0/voc/nexus/search/",
      "filter":"nxs:filter",
      "path":"nxs:path",
      "value":"nxs:value",
      "op":"nxs:op",
      "providerId": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/providerId" 
  },
  "filter": {
    "path": "providerId",
    "op": "eq",
    "value": "1012"
  }
}
```
The two above json-ld documents are not equivalent as it can be verified by expanding them using the [ json-ld playground](https://json-ld.org/playground/)).

```
[
  {
    "http://localhost/v0/voc/nexus/search/filter": [
      {
        "http://localhost/v0/voc/nexus/search/op": [
          {
            "@value": "eq"
          }
        ],
        "http://localhost/v0/voc/nexus/search/path": [
          {
            "@value": "foo:providerId"
          }
        ],
        "http://localhost/v0/voc/nexus/search/value": [
          {
            "@value": "1012"
          }
        ]
      }
    ]
  }
]
```

is not equivalent to:

```
[
  {
    "http://localhost/v0/voc/nexus/search/filter": [
      {
        "http://localhost/v0/voc/nexus/search/op": [
          {
            "@value": "eq"
          }
        ],
        "http://localhost/v0/voc/nexus/search/path": [
          {
            "@value": "providerId"
          }
        ],
        "http://localhost/v0/voc/nexus/search/value": [
          {
            "@value": "1012"
          }
        ]
      }
    ]
  }
]
```

As noticed in the two expanded forms, the "http://localhost/v0/voc/nexus/search/path" property values (in bold) are not identical. And most importantly those values become literals when expanded instead of valid URIs. Hence the issue. 
So the way the  [default @context](https://github.com/BlueBrain/nexus-kg/blob/501d73480fe4e47442354943cbcc3c00ef730d80/modules/indexing/src/main/scala/ch/epfl/bluebrain/nexus/kg/indexing/filtering/Filter.scala#L33) is implemented should be changed in order to create the right default @context which is:

```
"@context": {
     "nxv":"http://localhost/v0/voc/nexus/core/",
     "nxs":"http://localhost/v0/voc/nexus/search/",
     "filter":"nxs:filter",
     "path":{
        "@type":"@id",
        "@id":"nxs:path"
      },
      "value":"nxs:value",
      "op":"nxs:op"
  }
```

The values of http://localhost/v0/voc/nexus/search/path are ids ("@type" = "@id") and not literals. 

The following prefix mapping in the second filter example will not work (right context or not) since it is aliasing a value of a property. A valid URI or CURIE should be used as value of the "http://localhost/v0/voc/nexus/search/path" property or @base should be present in the @context if  "providerId" is used as its value.

```
 "providerId": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/providerId" 
```

The expanded form of the http://localhost/v0/voc/nexus/search/path should look like:

"http://localhost/v0/voc/nexus/search/path": [{
            "@id": "https://bbp-nexus.epfl.ch/dev/v0/voc/experiment/core/providerId"
}]

With the new filter default @context described above, the [asUri](https://github.com/BlueBrain/nexus-kg/blob/501d73480fe4e47442354943cbcc3c00ef730d80/modules/indexing/src/main/scala/ch/epfl/bluebrain/nexus/kg/indexing/filtering/Filter.scala#L57) function should be changed to properly check whether the node is a literal node (n.isLiteral is true) or a URI  one (n.isURI is true). In case of a URI node a call to node.getURI is enough to get the URI. There is no need to apply again the prefix mapping when the son-ld is already loaded in a Jena graph.
